private import TreeSitter

// Re-export all the nodes in the Solidity Query Language Library (QLL) file autogenerated by Tree-sitter
// This will give us a more readable foundation to build the library classes off of
cached private newtype TAstNode = 
  TAnyPragmaToken(Solidity::AnyPragmaToken e)
  or
  TArrayAccess(Solidity::ArrayAccess e)
  or
  TAssemblyFlags(Solidity::AssemblyFlags e)
  or
  TAssemblyStatement(Solidity::AssemblyStatement e)
  or
  TAssignmentExpression(Solidity::AssignmentExpression e)
  or
  TAugmentedAssignmentExpression(Solidity::AugmentedAssignmentExpression e)
  or
  TBinaryExpression(Solidity::BinaryExpression e)
  or
  TBlockStatement(Solidity::BlockStatement e)
  or
  TBooleanLiteral(Solidity::BooleanLiteral e)
  or
  TBreakStatement(Solidity::BreakStatement e)
  or
  TCallArgument(Solidity::CallArgument e)
  or
  TCallExpression(Solidity::CallExpression e)
  or
  TCallStructArgument(Solidity::CallStructArgument e)
  or
  TCatchClause(Solidity::CatchClause e)
  or
  TComment(Solidity::Comment e)
  or
  TConstantVariableDeclaration(Solidity::ConstantVariableDeclaration e)
  or
  TConstructorDefinition(Solidity::ConstructorDefinition e)
  or
  TContinueStatement(Solidity::ContinueStatement e)
  or
  TContractBody(Solidity::ContractBody e)
  or
  TContractDeclaration(Solidity::ContractDeclaration e)
  or
  TDoWhileStatement(Solidity::DoWhileStatement e)
  or
  TEmitStatement(Solidity::EmitStatement e)
  or
  TEnumBody(Solidity::EnumBody e)
  or
  TEnumDeclaration(Solidity::EnumDeclaration e)
  or
  TEnumValue(Solidity::EnumValue e)
  or
  TErrorDeclaration(Solidity::ErrorDeclaration e)
  or
  TErrorParameter(Solidity::ErrorParameter e)
  or
  TEventDefinition(Solidity::EventDefinition e)
  or
  TEventParameter(Solidity::EventParameter e)
  or
  TSolExpression(Solidity::Expression e)
  or
  TExpressionStatement(Solidity::ExpressionStatement e)
  or
  TFalse(Solidity::False e)
  or
  TFallbackReceiveDefinition(Solidity::FallbackReceiveDefinition e)
  or
  TForStatement(Solidity::ForStatement e)
  or
  TFunctionBody(Solidity::FunctionBody e)
  or
  TFunctionDefinition(Solidity::FunctionDefinition e)
  or
  THexStringLiteral(Solidity::HexStringLiteral e)
  or
  TIdentifier(Solidity::Identifier e)
  or
  TIfStatement(Solidity::IfStatement e)
  or
  TImmutable(Solidity::Immutable e)
  or
  TImportDirective(Solidity::ImportDirective e)
  or
  TInheritanceSpecifier(Solidity::InheritanceSpecifier e)
  or
  TInlineArrayExpression(Solidity::InlineArrayExpression e)
  or
  TInterfaceDeclaration(Solidity::InterfaceDeclaration e)
  or
  TLayoutSpecifier(Solidity::LayoutSpecifier e)
  or
  TLibraryDeclaration(Solidity::LibraryDeclaration e)
  or
  TMemberExpression(Solidity::MemberExpression e)
  or
  TMetaTypeExpression(Solidity::MetaTypeExpression e)
  or
  TModifierDefinition(Solidity::ModifierDefinition e)
  or
  TModifierInvocation(Solidity::ModifierInvocation e)
  or
  TNewExpression(Solidity::NewExpression e)
  or
  TNumberLiteral(Solidity::NumberLiteral e)
  or
  TNumberUnit(Solidity::NumberUnit e)
  or
  TOverrideSpecifier(Solidity::OverrideSpecifier e)
  or
  TParameter(Solidity::Parameter e)
  or
  TParenthesizedExpression(Solidity::ParenthesizedExpression e)
  or
  TPayableConversionExpression(Solidity::PayableConversionExpression e)
  or
  TPragmaDirective(Solidity::PragmaDirective e)
  or
  TPragmaValue(Solidity::PragmaValue e)
  or
  TPrimitiveType(Solidity::PrimitiveType e)
  or
  TReservedWord(Solidity::ReservedWord e)
  or
  TReturnParameter(Solidity::ReturnParameter e)
  or
  TReturnStatement(Solidity::ReturnStatement e)
  or
  TReturnTypeDefinition(Solidity::ReturnTypeDefinition e)
  or
  TRevertArguments(Solidity::RevertArguments e)
  or
  TRevertStatement(Solidity::RevertStatement e)
  or
  TSliceAccess(Solidity::SliceAccess e)
  or
  TSolidityPragmaToken(Solidity::SolidityPragmaToken e)
  or
  TSolidityVersion(Solidity::SolidityVersion e)
  or
  TSolidityVersionComparisonOperator(Solidity::SolidityVersionComparisonOperator e)
  or
  TSourceFile(Solidity::SourceFile e)
  or
  TStateLocation(Solidity::StateLocation e)
  or
  TStateMutability(Solidity::StateMutability e)
  or
  TStateVariableDeclaration(Solidity::StateVariableDeclaration e)
  or
  TSolStatement(Solidity::Statement e)
  or
  TString(Solidity::String e)
  or
  TStringLiteral(Solidity::StringLiteral e)
  or
  TStructBody(Solidity::StructBody e)
  or
  TStructDeclaration(Solidity::StructDeclaration e)
  or
  TStructExpression(Solidity::StructExpression e)
  or
  TStructFieldAssignment(Solidity::StructFieldAssignment e)
  or
  TStructMember(Solidity::StructMember e)
  or
  TTernaryExpression(Solidity::TernaryExpression e)
  or
  TSolToken(Solidity::Token e)
  or
  TTrue(Solidity::True e)
  or
  TTryStatement(Solidity::TryStatement e)
  or
  TTupleExpression(Solidity::TupleExpression e)
  or
  TTypeAlias(Solidity::TypeAlias e)
  or
  TTypeCastExpression(Solidity::TypeCastExpression e)
  or
  TTypeName(Solidity::TypeName e)
  or
  TUnaryExpression(Solidity::UnaryExpression e)
  or
  TUnchecked(Solidity::Unchecked e)
  or
  TUnicodeStringLiteral(Solidity::UnicodeStringLiteral e)
  or
  TUpdateExpression(Solidity::UpdateExpression e)
  or
  TUserDefinableOperator(Solidity::UserDefinableOperator e)
  or
  TUserDefinedType(Solidity::UserDefinedType e)
  or
  TUserDefinedTypeDefinition(Solidity::UserDefinedTypeDefinition e)
  or
  TUsingAlias(Solidity::UsingAlias e)
  or
  TUsingDirective(Solidity::UsingDirective e)
  or
  TVariableDeclaration(Solidity::VariableDeclaration e)
  or
  TVariableDeclarationStatement(Solidity::VariableDeclarationStatement e)
  or
  TVariableDeclarationTuple(Solidity::VariableDeclarationTuple e)
  or
  TVirtual(Solidity::Virtual e)
  or
  TVisibility(Solidity::Visibility e)
  or
  TWhileStatement(Solidity::WhileStatement e)
  or
  TYulAssignment(Solidity::YulAssignment e)
  or
  TYulBlock(Solidity::YulBlock e)
  or
  TYulBoolean(Solidity::YulBoolean e)
  or
  TYulBreak(Solidity::YulBreak e)
  or
  TYulContinue(Solidity::YulContinue e)
  or
  TYulDecimalNumber(Solidity::YulDecimalNumber e)
  or
  TYulEvmBuiltin(Solidity::YulEvmBuiltin e)
  or
  TYulForStatement(Solidity::YulForStatement e)
  or
  TYulFunctionCall(Solidity::YulFunctionCall e)
  or
  TYulFunctionDefinition(Solidity::YulFunctionDefinition e)
  or
  TYulHexNumber(Solidity::YulHexNumber e)
  or
  TYulHexStringLiteral(Solidity::YulHexStringLiteral e)
  or
  TYulIdentifier(Solidity::YulIdentifier e)
  or
  TYulIfStatement(Solidity::YulIfStatement e)
  or
  TYulLabel(Solidity::YulLabel e)
  or
  TYulLeave(Solidity::YulLeave e)
  or
  TYulPath(Solidity::YulPath e)
  or
  TYulStringLiteral(Solidity::YulStringLiteral e)
  or
  TYulSwitchStatement(Solidity::YulSwitchStatement e)
  or
  TYulVariableDeclaration(Solidity::YulVariableDeclaration e)

// Conversion function from TAstNode to Solidity::AstNode
Solidity::AstNode toTreeSitter(TAstNode node) {
  TAnyPragmaToken(result) = node
  or
  TArrayAccess(result) = node
  or
  TAssemblyFlags(result) = node
  or
  TAssemblyStatement(result) = node
  or
  TAssignmentExpression(result) = node
  or
  TAugmentedAssignmentExpression(result) = node
  or
  TBinaryExpression(result) = node
  or
  TBlockStatement(result) = node
  or
  TBooleanLiteral(result) = node
  or
  TBreakStatement(result) = node
  or
  TCallArgument(result) = node
  or
  TCatchClause(result) = node
  or
  TComment(result) = node
  or
  TConstantVariableDeclaration(result) = node
  or
  TConstructorDefinition(result) = node
  or
  TContinueStatement(result) = node
  or
  TContractBody(result) = node
  or
  TContractDeclaration(result) = node
  or
  TDoWhileStatement(result) = node
  or
  TEmitStatement(result) = node
  or
  TEnumBody(result) = node
  or
  TEnumDeclaration(result) = node
  or
  TEnumValue(result) = node
  or
  TErrorDeclaration(result) = node
  or
  TErrorParameter(result) = node
  or
  TEventDefinition(result) = node
  or
  TEventParameter(result) = node
  or
  TSolExpression(result) = node
  or
  TExpressionStatement(result) = node
  or
  TFalse(result) = node
  or
  TFallbackReceiveDefinition(result) = node
  or
  TForStatement(result) = node
  or
  TFunctionBody(result) = node
  or
  TFunctionDefinition(result) = node
  or
  THexStringLiteral(result) = node
  or
  TIdentifier(result) = node
  or
  TIfStatement(result) = node
  or
  TImmutable(result) = node
  or
  TImportDirective(result) = node
  or
  TInheritanceSpecifier(result) = node
  or
  TInlineArrayExpression(result) = node
  or
  TInterfaceDeclaration(result) = node
  or
  TLayoutSpecifier(result) = node
  or
  TLibraryDeclaration(result) = node
  or
  TMemberExpression(result) = node
  or
  TMetaTypeExpression(result) = node
  or
  TModifierDefinition(result) = node
  or
  TModifierInvocation(result) = node
  or
  TNewExpression(result) = node
  or
  TNumberLiteral(result) = node
  or
  TNumberUnit(result) = node
  or
  TOverrideSpecifier(result) = node
  or
  TParameter(result) = node
  or
  TParenthesizedExpression(result) = node
  or
  TPayableConversionExpression(result) = node
  or
  TPragmaDirective(result) = node
  or
  TPragmaValue(result) = node
  or
  TPrimitiveType(result) = node
  or
  TReservedWord(result) = node
  or
  TReturnParameter(result) = node
  or
  TReturnStatement(result) = node
  or
  TReturnTypeDefinition(result) = node
  or
  TRevertArguments(result) = node
  or
  TRevertStatement(result) = node
  or
  TSliceAccess(result) = node
  or
  TSolidityPragmaToken(result) = node
  or
  TSolidityVersion(result) = node
  or
  TSolidityVersionComparisonOperator(result) = node
  or
  TSourceFile(result) = node
  or
  TStateLocation(result) = node
  or
  TStateMutability(result) = node
  or
  TStateVariableDeclaration(result) = node
  or
  TSolStatement(result) = node
  or
  TString(result) = node
  or
  TStringLiteral(result) = node
  or
  TStructBody(result) = node
  or
  TStructDeclaration(result) = node
  or
  TStructExpression(result) = node
  or
  TStructFieldAssignment(result) = node
  or
  TStructMember(result) = node
  or
  TTernaryExpression(result) = node
  or
  TSolToken(result) = node
  or
  TTrue(result) = node
  or
  TTryStatement(result) = node
  or
  TTupleExpression(result) = node
  or
  TTypeAlias(result) = node
  or
  TTypeCastExpression(result) = node
  or
  TTypeName(result) = node
  or
  TUnaryExpression(result) = node
  or
  TUnchecked(result) = node
  or
  TUnicodeStringLiteral(result) = node
  or
  TUpdateExpression(result) = node
  or
  TUserDefinableOperator(result) = node
  or
  TUserDefinedType(result) = node
  or
  TUserDefinedTypeDefinition(result) = node
  or
  TUsingAlias(result) = node
  or
  TUsingDirective(result) = node
  or
  TVariableDeclaration(result) = node
  or
  TVariableDeclarationStatement(result) = node
  or
  TVariableDeclarationTuple(result) = node
  or
  TVirtual(result) = node
  or
  TVisibility(result) = node
  or
  TWhileStatement(result) = node
  or
  TYulAssignment(result) = node
  or
  TYulBlock(result) = node
  or
  TYulBoolean(result) = node
  or
  TYulBreak(result) = node
  or
  TYulContinue(result) = node
  or
  TYulDecimalNumber(result) = node
  or
  TYulEvmBuiltin(result) = node
  or
  TYulForStatement(result) = node
  or
  TYulFunctionCall(result) = node
  or
  TYulFunctionDefinition(result) = node
  or
  TYulHexNumber(result) = node
  or
  TYulHexStringLiteral(result) = node
  or
  TYulIdentifier(result) = node
  or
  TYulIfStatement(result) = node
  or
  TYulLabel(result) = node
  or
  TYulLeave(result) = node
  or
  TYulPath(result) = node
  or
  TYulStringLiteral(result) = node
  or
  TYulSwitchStatement(result) = node
  or
  TYulVariableDeclaration(result) = node
}

// Group Solidity-specific types into high-level classes
class TExpression = 
  TArrayAccess
  or
  TAssignmentExpression
  or
  TAugmentedAssignmentExpression
  or
  TBinaryExpression
  or
  TBooleanLiteral
  or
  TCallExpression
  or
  TCallStructArgument
  or
  TSolExpression
  or
  TInlineArrayExpression
  or
  TMemberExpression
  or
  TMetaTypeExpression
  or
  TNewExpression
  or
  TNumberLiteral
  or
  TParenthesizedExpression
  or
  TPayableConversionExpression
  or
  TSliceAccess
  or
  TStringLiteral
  or
  TStructExpression
  or
  TTernaryExpression
  or
  TTupleExpression
  or
  TTypeCastExpression
  or
  TUnaryExpression
  or
  TUpdateExpression
  or
  TVariableDeclaration
  or
  TYulIdentifier
  or
  TYulStringLiteral;

class TStatement = 
  TAssemblyStatement
  or
  TBlockStatement
  or
  TBreakStatement
  or
  TContinueStatement
  or
  TDoWhileStatement
  or
  TEmitStatement
  or
  TExpressionStatement
  or
  TForStatement
  or
  TIfStatement
  or
  TRevertStatement
  or
  TTryStatement
  or
  TWhileStatement
  or
  TYulBlock
  or
  TYulForStatement
  or
  TYulIfStatement
  or
  TYulSwitchStatement;

class TDeclaration = 
  TConstantVariableDeclaration
  or
  TConstructorDefinition
  or
  TContractDeclaration
  or
  TEnumDeclaration
  or
  TErrorDeclaration
  or
  TEventDefinition
  or
  TFunctionDefinition
  or
  TInterfaceDeclaration
  or
  TLibraryDeclaration
  or
  TModifierDefinition
  or
  TStateVariableDeclaration
  or
  TStructDeclaration
  or
  TTypeAlias
  or
  TYulFunctionDefinition;

class TToken = 
  TComment
  or
  TFalse
  or
  THexStringLiteral
  or
  TIdentifier
  or
  TImmutable
  or
  TNumberUnit
  or
  TPragmaValue
  or
  TPrimitiveType
  or
  TReservedWord
  or
  TSolidityVersion
  or
  TSolidityVersionComparisonOperator
  or
  TStateLocation
  or
  TStateMutability
  or
  TString
  or
  TTrue
  or
  TUnchecked
  or
  TUnicodeStringLiteral
  or
  TUserDefinableOperator
  or
  TVirtual
  or
  TVisibility
  or
  TYulBoolean
  or
  TYulBreak
  or
  TYulContinue
  or
  TYulDecimalNumber
  or
  TYulEvmBuiltin
  or
  TYulHexNumber
  or
  TYulHexStringLiteral
  or
  TYulLeave;

class TContractElement = 
  TContractBody
  or
  TContractDeclaration
  or
  TInterfaceDeclaration
  or
  TLibraryDeclaration;

class TFunctionElement = 
  TFunctionDefinition
  or
  TModifierDefinition
  or
  TConstructorDefinition
  or
  TYulFunctionDefinition;

class TYulElement = 
  TYulAssignment
  or
  TYulBlock
  or
  TYulForStatement
  or
  TYulFunctionCall
  or
  TYulFunctionDefinition
  or
  TYulIfStatement
  or
  TYulLabel
  or
  TYulSwitchStatement
  or
  TYulVariableDeclaration;
