private import TreeSitter

class SolToken =
  @solidity_reserved_word
  or
  @solidity_token_any_source_type
  or
  @solidity_token_break_statement
  or
  @solidity_token_comment
  or
  @solidity_token_continue_statement
  or
  @solidity_token_decimal_number
  or
  @solidity_token_enum_value
  or
  @solidity_token_false
  or
  @solidity_token_hex_number
  or
  @solidity_token_hex_string_literal
  or
  @solidity_token_identifier
  or
  @solidity_token_immutable
  or
  @solidity_token_number_unit
  or
  @solidity_token_pragma_value
  or
  @solidity_token_primitive_type
  or
  @solidity_token_solidity_version
  or
  @solidity_token_state_location
  or
  @solidity_token_state_mutability
  or
  @solidity_token_string
  or
  @solidity_token_true
  or
  @solidity_token_unchecked
  or
  @solidity_token_unicode_string_literal
  or
  @solidity_token_user_definable_operator
  or
  @solidity_token_virtual
  or
  @solidity_token_visibility
  or
  @solidity_token_yul_boolean
  or
  @solidity_token_yul_break
  or
  @solidity_token_yul_continue
  or
  @solidity_token_yul_decimal_number
  or
  @solidity_token_yul_evm_builtin
  or
  @solidity_token_yul_hex_number
  or
  @solidity_token_yul_hex_string_literal
  or
  @solidity_token_yul_leave;

Solidity::Token toToken(SolToken node) {
  result = node
}

// Re-export all the nodes in the Solidity Query Language Library (QLL) file autogenerated by Tree-sitter
// This will give us a more readable foundation to build the library classes off of
cached newtype TAstNode = 
  // Add the abstracted SolToken class to the TAstNode type, which ensures that all tokens roll back up to AstNode
  TReservedWord(SolToken e) { e instanceof @solidity_reserved_word }
  or
  TAnySourceType(SolToken e) { e instanceof @solidity_token_any_source_type }
  or
  TBreakStatement(SolToken e) { e instanceof @solidity_token_break_statement }
  or
  TComment(SolToken e) { e instanceof @solidity_token_comment }
  or
  TContinueStatement(SolToken e) { e instanceof @solidity_token_continue_statement }
  or
  TDecimalNumber(SolToken e) { e instanceof @solidity_token_decimal_number }
  or
  TEnumValue(SolToken e) { e instanceof @solidity_token_enum_value }
  or
  TFalse(SolToken e) { e instanceof @solidity_token_false }
  or
  THexNumber(SolToken e) { e instanceof @solidity_token_hex_number }
  or
  THexStringLiteral(SolToken e) { e instanceof @solidity_token_hex_string_literal }
  or
  TIdentifier(SolToken e) { e instanceof @solidity_token_identifier }
  or
  TImmutable(SolToken e) { e instanceof @solidity_token_immutable }
  or
  TNumberUnit(SolToken e) { e instanceof @solidity_token_number_unit }
  or
  TPragmaValue(SolToken e) { e instanceof @solidity_token_pragma_value }
  or
  TPrimitiveType(SolToken e) { e instanceof @solidity_token_primitive_type }
  or
  TSolidityVersion(SolToken e) { e instanceof @solidity_token_solidity_version }
  or
  TStateLocation(SolToken e) { e instanceof @solidity_token_state_location }
  or
  TStateMutability(SolToken e) { e instanceof @solidity_token_state_mutability }
  or
  TString(SolToken e) { e instanceof @solidity_token_string }
  or
  TTrue(SolToken e) { e instanceof @solidity_token_true }
  or
  TUnchecked(SolToken e) { e instanceof @solidity_token_unchecked }
  or
  TUnicodeStringLiteral(SolToken e) { e instanceof @solidity_token_unicode_string_literal }
  or
  TUserDefinableOperator(SolToken e) { e instanceof @solidity_token_user_definable_operator }
  or
  TVirtual(SolToken e) { e instanceof @solidity_token_virtual }
  or
  TVisibility(SolToken e) { e instanceof @solidity_token_visibility }
  or
  TYulBoolean(SolToken e) { e instanceof @solidity_token_yul_boolean }
  or
  TYulBreak(SolToken e) { e instanceof @solidity_token_yul_break }
  or
  TYulContinue(SolToken e) { e instanceof @solidity_token_yul_continue }
  or
  TYulDecimalNumber(SolToken e) { e instanceof @solidity_token_yul_decimal_number }
  or
  TYulEvmBuiltin(SolToken e) { e instanceof @solidity_token_yul_evm_builtin }
  or
  TYulHexNumber(SolToken e) { e instanceof @solidity_token_yul_hex_number }
  or
  TYulHexStringLiteral(SolToken e) { e instanceof @solidity_token_yul_hex_string_literal }
  or
  TYulLeave(SolToken e) { e instanceof @solidity_token_yul_leave }
  or
  TAnyPragmaToken(Solidity::AnyPragmaToken e)
  or
  TArrayAccess(Solidity::ArrayAccess e)
  or
  TAssemblyFlags(Solidity::AssemblyFlags e)
  or
  TSolAssemblyStatement(Solidity::AssemblyStatement e)
  or
  TAssignmentExpression(Solidity::AssignmentExpression e)
  or
  TAugmentedAssignmentExpression(Solidity::AugmentedAssignmentExpression e)
  or
  TBinaryExpression(Solidity::BinaryExpression e)
  or
  TBlockStatement(Solidity::BlockStatement e)
  or
  TBooleanLiteral(Solidity::BooleanLiteral e)
  or
  TCallArgument(Solidity::CallArgument e)
  or
  TCallExpression(Solidity::CallExpression e)
  or
  TCallStructArgument(Solidity::CallStructArgument e)
  or
  TCatchClause(Solidity::CatchClause e)
  or
  TConstantVariableDeclaration(Solidity::ConstantVariableDeclaration e)
  or
  TConstructorDefinition(Solidity::ConstructorDefinition e)
  or
  TContractBody(Solidity::ContractBody e)
  or
  TContractDeclaration(Solidity::ContractDeclaration e)
  or
  TDoWhileStatement(Solidity::DoWhileStatement e)
  or
  TEmitStatement(Solidity::EmitStatement e)
  or
  TEnumBody(Solidity::EnumBody e)
  or
  TEnumDeclaration(Solidity::EnumDeclaration e)
  or
  TErrorDeclaration(Solidity::ErrorDeclaration e)
  or
  TErrorParameter(Solidity::ErrorParameter e)
  or
  TEventDefinition(Solidity::EventDefinition e)
  or
  TEventParameter(Solidity::EventParameter e)
  or
  TSolExpression(Solidity::Expression e)
  or
  TExpressionStatement(Solidity::ExpressionStatement e)
  or
  TFallbackReceiveDefinition(Solidity::FallbackReceiveDefinition e)
  or
  TForStatement(Solidity::ForStatement e)
  or
  TFunctionBody(Solidity::FunctionBody e)
  or
  TFunctionDefinition(Solidity::FunctionDefinition e)
  or
  TIfStatement(Solidity::IfStatement e)
  or
  TImportDirective(Solidity::ImportDirective e)
  or
  TInheritanceSpecifier(Solidity::InheritanceSpecifier e)
  or
  TInlineArrayExpression(Solidity::InlineArrayExpression e)
  or
  TInterfaceDeclaration(Solidity::InterfaceDeclaration e)
  or
  TLayoutSpecifier(Solidity::LayoutSpecifier e)
  or
  TLibraryDeclaration(Solidity::LibraryDeclaration e)
  or
  TMemberExpression(Solidity::MemberExpression e)
  or
  TMetaTypeExpression(Solidity::MetaTypeExpression e)
  or
  TModifierDefinition(Solidity::ModifierDefinition e)
  or
  TModifierInvocation(Solidity::ModifierInvocation e)
  or
  TNewExpression(Solidity::NewExpression e)
  or
  TNumberLiteral(Solidity::NumberLiteral e)
  or
  TOverrideSpecifier(Solidity::OverrideSpecifier e)
  or
  TParameter(Solidity::Parameter e)
  or
  TParenthesizedExpression(Solidity::ParenthesizedExpression e)
  or
  TPayableConversionExpression(Solidity::PayableConversionExpression e)
  or
  TPragmaDirective(Solidity::PragmaDirective e)
  or
  TReturnParameter(Solidity::ReturnParameter e)
  or
  TReturnStatement(Solidity::ReturnStatement e)
  or
  TReturnTypeDefinition(Solidity::ReturnTypeDefinition e)
  or
  TRevertArguments(Solidity::RevertArguments e)
  or
  TRevertStatement(Solidity::RevertStatement e)
  or
  TSliceAccess(Solidity::SliceAccess e)
  or
  TSolidityPragmaToken(Solidity::SolidityPragmaToken e)
  or
  TSolidityVersionComparisonOperator(Solidity::SolidityVersionComparisonOperator e)
  or
  TSourceFile(Solidity::SourceFile e)
  or
  TStateVariableDeclaration(Solidity::StateVariableDeclaration e)
  or
  TSolStatement(Solidity::Statement e)
  or
  TStringLiteral(Solidity::StringLiteral e)
  or
  TStructBody(Solidity::StructBody e)
  or
  TStructDeclaration(Solidity::StructDeclaration e)
  or
  TStructExpression(Solidity::StructExpression e)
  or
  TStructFieldAssignment(Solidity::StructFieldAssignment e)
  or
  TStructMember(Solidity::StructMember e)
  or
  TTernaryExpression(Solidity::TernaryExpression e)
  or
  TTryStatement(Solidity::TryStatement e)
  or
  TTupleExpression(Solidity::TupleExpression e)
  or
  TTypeAlias(Solidity::TypeAlias e)
  or
  TTypeCastExpression(Solidity::TypeCastExpression e)
  or
  TTypeName(Solidity::TypeName e)
  or
  TUnaryExpression(Solidity::UnaryExpression e)
  or
  TUpdateExpression(Solidity::UpdateExpression e)
  or
  TUserDefinedType(Solidity::UserDefinedType e)
  or
  TUserDefinedTypeDefinition(Solidity::UserDefinedTypeDefinition e)
  or
  TUsingAlias(Solidity::UsingAlias e)
  or
  TUsingDirective(Solidity::UsingDirective e)
  or
  TVariableDeclaration(Solidity::VariableDeclaration e)
  or
  TVariableDeclarationStatement(Solidity::VariableDeclarationStatement e)
  or
  TVariableDeclarationTuple(Solidity::VariableDeclarationTuple e)
  or
  TWhileStatement(Solidity::WhileStatement e)
  or
  TYulAssignment(Solidity::YulAssignment e)
  or
  TYulBlock(Solidity::YulBlock e)
  or
  TYulForStatement(Solidity::YulForStatement e)
  or
  TYulFunctionCall(Solidity::YulFunctionCall e)
  or
  TYulFunctionDefinition(Solidity::YulFunctionDefinition e)
  or
  TYulIdentifier(Solidity::YulIdentifier e)
  or
  TYulIfStatement(Solidity::YulIfStatement e)
  or
  TYulLabel(Solidity::YulLabel e)
  or
  TYulPath(Solidity::YulPath e)
  or
  TYulStringLiteral(Solidity::YulStringLiteral e)
  or
  TYulSwitchStatement(Solidity::YulSwitchStatement e)
  or
  TYulVariableDeclaration(Solidity::YulVariableDeclaration e)

// Conversion function from TAstNode to Solidity::AstNode
Solidity::AstNode toTreeSitter(TAstNode node) {
  TReservedWord(result) = node
  or
  TAnySourceType(result) = node
  or
  TBreakStatement(result) = node
  or
  TComment(result) = node
  or
  TContinueStatement(result) = node
  or
  TDecimalNumber(result) = node
  or
  TEnumValue(result) = node
  or
  TFalse(result) = node
  or
  THexNumber(result) = node
  or
  THexStringLiteral(result) = node
  or
  TIdentifier(result) = node
  or
  TImmutable(result) = node
  or
  TNumberUnit(result) = node
  or
  TPragmaValue(result) = node
  or
  TPrimitiveType(result) = node
  or
  TSolidityVersion(result) = node
  or
  TStateLocation(result) = node
  or
  TStateMutability(result) = node
  or
  TString(result) = node
  or
  TTrue(result) = node
  or
  TUnchecked(result) = node
  or
  TUnicodeStringLiteral(result) = node
  or
  TUserDefinableOperator(result) = node
  or
  TVirtual(result) = node
  or
  TVisibility(result) = node
  or
  TYulBoolean(result) = node
  or
  TYulBreak(result) = node
  or
  TYulContinue(result) = node
  or
  TYulDecimalNumber(result) = node
  or
  TYulEvmBuiltin(result) = node
  or
  TYulHexNumber(result) = node
  or
  TYulHexStringLiteral(result) = node
  or
  TYulLeave(result) = node
  or
  TAnyPragmaToken(result) = node
  or
  TArrayAccess(result) = node
  or
  TAssemblyFlags(result) = node
  or
  TSolAssemblyStatement(result) = node
  or
  TAssignmentExpression(result) = node
  or
  TAugmentedAssignmentExpression(result) = node
  or
  TBinaryExpression(result) = node
  or
  TBlockStatement(result) = node
  or
  TBooleanLiteral(result) = node
  or
  TCallArgument(result) = node
  or
  TCatchClause(result) = node
  or
  TConstantVariableDeclaration(result) = node
  or
  TConstructorDefinition(result) = node
  or
  TContractBody(result) = node
  or
  TContractDeclaration(result) = node
  or
  TDoWhileStatement(result) = node
  or
  TEmitStatement(result) = node
  or
  TEnumBody(result) = node
  or
  TEnumDeclaration(result) = node
  or
  TErrorDeclaration(result) = node
  or
  TErrorParameter(result) = node
  or
  TEventDefinition(result) = node
  or
  TEventParameter(result) = node
  or
  TSolExpression(result) = node
  or
  TExpressionStatement(result) = node
  or
  TFallbackReceiveDefinition(result) = node
  or
  TForStatement(result) = node
  or
  TFunctionBody(result) = node
  or
  TFunctionDefinition(result) = node
  or
  TIfStatement(result) = node
  or
  TImportDirective(result) = node
  or
  TInheritanceSpecifier(result) = node
  or
  TInlineArrayExpression(result) = node
  or
  TInterfaceDeclaration(result) = node
  or
  TLayoutSpecifier(result) = node
  or
  TLibraryDeclaration(result) = node
  or
  TMemberExpression(result) = node
  or
  TMetaTypeExpression(result) = node
  or
  TModifierDefinition(result) = node
  or
  TModifierInvocation(result) = node
  or
  TNewExpression(result) = node
  or
  TNumberLiteral(result) = node
  or
  TOverrideSpecifier(result) = node
  or
  TParameter(result) = node
  or
  TParenthesizedExpression(result) = node
  or
  TPayableConversionExpression(result) = node
  or
  TPragmaDirective(result) = node
  or
  TReturnParameter(result) = node
  or
  TReturnStatement(result) = node
  or
  TReturnTypeDefinition(result) = node
  or
  TRevertArguments(result) = node
  or
  TRevertStatement(result) = node
  or
  TSliceAccess(result) = node
  or
  TSolidityPragmaToken(result) = node
  or
  TSolidityVersionComparisonOperator(result) = node
  or
  TSourceFile(result) = node
  or
  TStateVariableDeclaration(result) = node
  or
  TSolStatement(result) = node
  or
  TStringLiteral(result) = node
  or
  TStructBody(result) = node
  or
  TStructDeclaration(result) = node
  or
  TStructExpression(result) = node
  or
  TStructFieldAssignment(result) = node
  or
  TStructMember(result) = node
  or
  TTernaryExpression(result) = node
  or
  TTryStatement(result) = node
  or
  TTupleExpression(result) = node
  or
  TTypeAlias(result) = node
  or
  TTypeCastExpression(result) = node
  or
  TTypeName(result) = node
  or
  TUnaryExpression(result) = node
  or
  TUpdateExpression(result) = node
  or
  TUserDefinedType(result) = node
  or
  TUserDefinedTypeDefinition(result) = node
  or
  TUsingAlias(result) = node
  or
  TUsingDirective(result) = node
  or
  TVariableDeclaration(result) = node
  or
  TVariableDeclarationStatement(result) = node
  or
  TVariableDeclarationTuple(result) = node
  or
  TWhileStatement(result) = node
  or
  TYulAssignment(result) = node
  or
  TYulBlock(result) = node
  or
  TYulForStatement(result) = node
  or
  TYulFunctionCall(result) = node
  or
  TYulFunctionDefinition(result) = node
  or
  TYulIdentifier(result) = node
  or
  TYulIfStatement(result) = node
  or
  TYulLabel(result) = node
  or
  TYulPath(result) = node
  or
  TYulStringLiteral(result) = node
  or
  TYulSwitchStatement(result) = node
  or
  TYulVariableDeclaration(result) = node
}

// Group Solidity-specific types into high-level classes
// All classes will be modeled after Solidity language grammar: https://docs.soliditylang.org/en/latest/grammar.html
class TExpression = 
  TArrayAccess
  or
  TAssignmentExpression
  or
  TAugmentedAssignmentExpression
  or
  TBinaryExpression
  or
  TCallExpression
  or
  TCallStructArgument
  or
  TInlineArrayExpression
  or
  TLiteral
  or
  TMemberExpression
  or
  TMetaTypeExpression
  or
  TNewExpression
  or
  TParenthesizedExpression
  or
  TPayableConversionExpression
  or
  TSliceAccess
  or
  TSolExpression
  or
  TStructExpression
  or
  TTernaryExpression
  or
  TTupleExpression
  or
  TTypeCastExpression
  or
  TUnaryExpression
  or
  TUpdateExpression
  or
  TVariableDeclaration
  or
  TYulExpression;

class TLiteral =
  TStringLiteral
  or
  TDecimalNumber
  or
  TNumberLiteral
  or
  TBooleanLiteral
  or
  THexStringLiteral
  or
  TUnicodeStringLiteral;

class TBlock = 
  TStatement
  or
  TUnchecked;

class TStatement = 
  TAssemblyStatement
  or
  TBlockStatement
  or
  TBreakStatement
  or
  TContinueStatement
  or
  TDoWhileStatement
  or
  TEmitStatement
  or
  TExpressionStatement
  or
  TForStatement
  or
  TIfStatement
  or
  TReturnStatement
  or
  TRevertStatement
  or
  TTryStatement
  or
  TVariableDeclarationStatement
  or
  TWhileStatement;

class TYulStatement = 
  TYulBlock
  or
  TYulVariableDeclaration
  or
  TYulAssignment
  or
  TYulFunctionCall
  or
  TYulIfStatement
  or
  TYulForStatement
  or
  TYulSwitchStatement
  or
  TYulLeave
  or
  TYulBreak
  or
  TYulContinue
  or
  TYulFunctionDefinition;

class TYulLiteral = 
  TYulDecimalNumber
  or
  TYulStringLiteral
  or
  TYulHexNumber
  or
  TYulBoolean
  or
  TYulHexStringLiteral;

class TYulExpression = 
  TYulPath
  or
  TYulFunctionCall
  or
  TYulLiteral;

class TDeclaration = 
  TConstantVariableDeclaration
  or
  TConstructorDefinition
  or
  TContractDeclaration
  or
  TEnumDeclaration
  or
  TErrorDeclaration
  or
  TEventDefinition
  or
  TFunctionDefinition
  or
  TInterfaceDeclaration
  or
  TLibraryDeclaration
  or
  TModifierDefinition
  or
  TStateVariableDeclaration
  or
  TStructDeclaration
  or
  TTypeAlias
  or
  TYulFunctionDefinition;

class TFunctionElement = 
  TFunctionDefinition
  or
  TModifierDefinition
  or
  TConstructorDefinition
  or
  TYulFunctionDefinition;

class TAssemblyStatement = 
  TSolAssemblyStatement
  or
  TAssemblyFlags
  or
  TYulStatement;

class TSourceUnit = 
  TImportDirective
  or
  TUsingDirective
  or
  TContractDeclaration
  or
  TInterfaceDeclaration
  or
  TLibraryDeclaration
  or
  TFunctionDefinition
  or
  TConstantVariableDeclaration
  or
  TStructDeclaration
  or
  TEnumDeclaration
  or
  TUserDefinedTypeDefinition
  or
  TErrorDeclaration
  or
  TEventDefinition;

class TContract = 
  TContractBody
  or
  TConstructorDefinition
  or
  TFunctionDefinition
  or
  TModifierDefinition
  or
  TFallbackReceiveDefinition
  or
  TStructDeclaration
  or
  TEnumDeclaration
  or
  TUserDefinedTypeDefinition
  or
  TStateVariableDeclaration
  or
  TEventDefinition
  or
  TErrorDeclaration
  or
  TUsingDirective;
